on: push
name: Continuous Integration
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          version: 20.x
      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm test
